app/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :comments

  match 'videos/search', to: 'videos#search',  via: 'get'
  resources :videos, only: [:show, :create]

  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :video
end

app/app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token

	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence:   true, format:     { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	
	has_secure_password
	validates :password, length: { minimum: 6 }

	has_many :comments
	has_many :videos
	
	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.digest(User.new_remember_token)
		end
end

app/app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@comment = Comment.new(comment_params)
      	if @comment.save
        	redirect_to @comment.video
      	end
	end

	def show
       @comment = Comment.find(params[:id])
   	end

	private
	
	def comment_params
		params.require(:comment).permit(:video_id, :body)
	end

end

app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	  def create
	    user = User.find_by(email: params[:session][:email].downcase)
	    if user && user.authenticate(params[:session][:password])
	      sign_in user
	      redirect_back_or user
	    else
	      flash.now[:error] = 'Invalid email/password combination'
	      render 'new'
	    end
	  end
	
	def destroy
		sign_out
		redirect_to root_url
	end

end

app/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :signed_in_user, only: [:edit, :update]
	before_action :correct_user,   only: [:edit, :update]

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			sign_in @user
			flash[:success] = "Welcome to the Sample App!"
			redirect_to @user
		else
			render 'new'
		end
	end

	def edit
	  @user = User.find(params[:id])
	end

	def update
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password,
			:password_confirmation)
	end

	# before filters
	
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

	def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/app/controllers/videos_controller.rb
class VideosController < ApplicationController

	def show
		@video = Video.find(params[:id])
		@comments = @video.comments
		@comment = @video.comments.build
		@youtube_id = /.*watch\?v=(.*)/.match(@video.url)[1]
	end

	def search
		@video = Video.new
	end

	def create
		@video = Video.where(url: video_params[:url]).first
		if @video
			redirect_to @video
		else
			@video = Video.new(video_params)
			if @video.save
				flash[:success] = "Video added"
				redirect_to @video
			else
				render 'new'
			end
		end
	end

	private

	def video_params
		params.require(:video).permit(:url)
	end

	def parse_video_url(url)

	end

end

app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/app/helpers/comments_helper.rb
module CommentsHelper
end

app/app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.digest(remember_token))
		self.current_user = user
	end

	def sign_out
		current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.digest(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
    	user == current_user
  	end

	def signed_in?
		!current_user.nil?
	end

	def redirect_back_or(default)
	    redirect_to(session[:return_to] || default)
	    session.delete(:return_to)
 	end

 	def store_location
    	session[:return_to] = request.url if request.get?
  	end


end

app/app/helpers/users_helper.rb
module UsersHelper
end

app/app/helpers/videos_helper.rb
module VideosHelper
end

app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/app/views/comments/_comment.html.erb
<div class="row">
  <div class="span6 offset3">
	<%= comment.body %>
  </div>
</div>

app/app/views/comments/_comment_form.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for @comment do |f| %>
      <%= f.text_field :body %>
      <%= f.hidden_field :video_id, :value => @comment.video_id %>

      <%= f.submit "Add comment", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
</head>

<body style="font-family: Arial;border: 0 none;">
  <%= render 'layouts/header' %>
  <%= yield %>

  <%= debug(params) if Rails.env.development? %>

</body>
</html>

app/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>

app/app/views/videos/search.html.erb
<% provide(:title, 'Add video') %>
<h1>Search for a video</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @video do |f| %>

      <%= f.label :url %>
      <%= f.text_field :url %>

      <%= f.submit "Search for video", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/app/views/videos/show.html.erb
<table>
	<tr>
		<td><div id="videoDiv">Loading...</div></td>
		<td valign="top">
			<div id="videoInfo">
				<p>Player state: <span id="playerState">--</span></p>
				<p>Current Time: <span id="videoCurrentTime">--:--</span> | Duration: <span id="videoDuration">--:--</span></p>
				<p>Bytes Total: <span id="bytesTotal">--</span> | Start Bytes: <span id="startBytes">--</span> | Bytes Loaded: <span id="bytesLoaded">--</span></p>
			</div>
		</td>
	</tr>
</table>

<% if @video.comments.any? %>
	<div class="row">
	  <div class="span6 offset3">
	    <%= render @comments %>
	  </div>
	</div>
<% end %>


<%= render 'comments/comment_form' %>


<style type="text/css">
	#videoDiv { 
		margin-right: 3px;
	}
	#videoInfo {
		margin-left: 3px;
	}
</style>
<script src="http://www.google.com/jsapi" type="text/javascript"></script>
<script type="text/javascript">
	google.load("swfobject", "2.1");
</script>    
<script type="text/javascript">
      /*
       * Polling the player for information
       */
       
      // Update a particular HTML element with a new value
      function updateHTML(elmId, value) {
      	document.getElementById(elmId).innerHTML = value;
      }
      
      // This function is called when an error is thrown by the player
      function onPlayerError(errorCode) {
      	alert("An error occured of type:" + errorCode);
      }
      
      // This function is called when the player changes state
      function onPlayerStateChange(newState) {
      	updateHTML("playerState", newState);
      }
      
      // Display information about the current state of the player
      function updatePlayerInfo() {
        // Also check that at least one function exists since when IE unloads the
        // page, it will destroy the SWF before clearing the interval.
        if(ytplayer && ytplayer.getDuration) {
        	updateHTML("videoDuration", ytplayer.getDuration());
        	updateHTML("videoCurrentTime", ytplayer.getCurrentTime());
        	updateHTML("bytesTotal", ytplayer.getVideoBytesTotal());
        	updateHTML("startBytes", ytplayer.getVideoStartBytes());
        	updateHTML("bytesLoaded", ytplayer.getVideoBytesLoaded());
        }
    }

      // This function is automatically called by the player once it loads
      function onYouTubePlayerReady(playerId) {
      	console.log("HELLO");
      	ytplayer = document.getElementById("ytPlayer");
        // This causes the updatePlayerInfo function to be called every 250ms to
        // get fresh data from the player
        setInterval(updatePlayerInfo, 250);
        updatePlayerInfo();
        ytplayer.addEventListener("onStateChange", "onPlayerStateChange");
        ytplayer.addEventListener("onError", "onPlayerError");
    }

      // The "main method" of this sample. Called when someone clicks "Run".
      function loadPlayer() {
        // The video to load
        var videoID = "<%= @youtube_id %>"
        // Lets Flash from another domain call JavaScript
        var params = { allowScriptAccess: "always" };
        // The element id of the Flash embed
        var atts = { id: "ytPlayer" };
        // All of the magic handled by SWFObject (http://code.google.com/p/swfobject/)
        swfobject.embedSWF("http://www.youtube.com/v/" + videoID + 
        	"?version=3&enablejsapi=1&playerapiid=player1", 
        	"videoDiv", "480", "295", "9", null, null, params, atts);
    }
    function _run() {
    	loadPlayer();
    }
    google.setOnLoadCallback(_run);
</script>